FUNCTION "LBP_CallBackAuxFunc" : Void
TITLE = Auxiliary functions
{ S7_Optimized_Access := 'FALSE' }
AUTHOR : SINUMERIK
FAMILY : SINUMERIK_ONE
VERSION : 6.15
//Call interface for users for auxiliary functions, the block is called on an event-driven basis in the basic program when new auxiliary functions are available
   VAR_INPUT 
      Chan : Byte;   // Index of channel
   END_VAR


BEGIN
END_FUNCTION

